### ISSUE TITLE
galerkin projector local ids

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio-distributed-linalg#15]
```py
  myNumMeshNodes   = int(myNumRows/dofsPerMnode)
  senddata         = myNumMeshNodes*np.ones(nRanks, dtype=np.int)
  meshNodesPerRank = np.empty(nRanks,dtype=np.int)
  if not nullComm:
    comm.Alltoall(senddata, meshNodesPerRank)
  
  myGidBeg = np.sum(meshNodesPerRank[:rank])
  myGlobalInds = np.arange(myNumMeshNodes) + myGidBeg 
```
@pjb236 
(1) why are you using `alltoall` instead of `allgather`? Alltoall is going to be expensive here because each rank is sending an array. If you want each rank to store an array with the num of mesh nodes for each rank, then you can just have each rank send a single int and do allgather. 
(2) anway, can we just avoid any mpi call here and use the methods in the MV class that I put in yesterday? 
if we can, I think we should avoid mpi call as much as possible 

If you have a multivector object, you can get what rows GIDs each rank has by doing: 
```py
A.minRowGidLocal()
A.maxRowGidLocal()
```
so i think that if we know how many dofs/cell we have, we can just use that info to figure out the DOF gids.

**Comment by pjb236** [comment]
I'll edit this to work with the MV class method to avoid alltoall calls. FYI there is a similar usage of alltoall in the leverage score routines that we might want to revisit as well.
