### ISSUE TITLE
sample mesh with leverage scores

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio-distributed-linalg#4]
section 5.1 of https://arxiv.org/pdf/1903.00911.pdf

**Comment by pjb236** [comment]
This can actually be pretty similar to what we came up with for DEIM, but we need some additional outputs since the sampling matrix is weighted. 

**Inputs**:

Use yaml file to prevent command line from being too long

Required:
```
residual-basis-root-name: root-file-name [string]
residual-basis-format: binary/ascii [string]
num-residual-basis-columns: number-of-basis-columns [int]
num-sample-mesh-nodes: number-of-desired-nodes [int]
num-mesh-nodes: number-of-mesh-nodes [int]
dofs-per-mesh-node: number-of-dofs-per-node [int]
leverage-score-beta: leverage-score-probability-mass-function-parameter [double]
```

Optional:
```
sample-mesh-seed-nodes: path-to-file [string]  Default: none. 
```
-sample-mesh-seed-nodes file should contain list of nodes (global ids) to include in the sample mesh. 

To run:

```
mpirun -np num-procs python leverage_score_sampling.py --input yaml-file-name
```

**Requirements**:

-All input integers should be non-zero and positive. 
-binary files have double-precision numbers (could add support for 32-bit later...)
-# of entries read in from residual basis files should be num-residual-basis-columns * num-mesh-nodes * does-per-mesh-node
-Fastest index should be nodal quantities (e.g. mass, momentum, energy for compressible fluids). 
-num-sample-mesh-nodes < num-mesh-nodes
-leverage-score-beta in [0,1]: 0=uniformly random sampling, 1=sampling from leverage scores only. 

**Outputs**:
Ascii file containing list of sample mesh nodes (full mesh global indices). 
Ascii file containing sparse matrix data for sampling matrix (indices and weights)

**Comment by pjb236** [comment]
Pseudo code in python, using numpy-type vector operations. These may need to be adjusted for parallelizing this code. 
```py
yaml_file_name = "hr.yaml" # or some other default name
# OR get yaml_file_name from command line

# read yaml file and assign entries to dictionary with input data
input_dict = readInputYaml(yaml_file_name)

Psi = readInResidualBasis(input_dict)

# initialize sample mesh node list
sample_mesh_nodes = []
num_init_nodes = 0
if input_dict.seed_nodes:
    sample_mesh_nodes += readSeedNodes(input_dict)    
    num_init_nodes = len(sample_mesh_nodes)

n_nodes_to_sample = input_dict.num_sample_mesh_nodes - num_init_nodes

# The following two routines could be merged into one:

# compute leverage scores for basis. The score is the squared L2 norm of each basis ROW
l_scores = computeLeverageScores(Psi)

# compute leverage score probability mass function (Eqn. 13 of paper)
l_score_pmf = createLeverageScorePMF(l_scores, input_dict)

# randomly sample remaining nodes
for i in range(n_nodes_to_sample):
    t_i = l_score_pmf.sample()
    sample_mesh_nodes.append( getMeshNodeFromVectorIndex(t_i))

# create sampling matrix object (object containing sparse matrix data)
# add entries for all dofs on each node in sample_mesh_nodes 
# magnitude of each entry should be 1 / sqrt(num_sample_mesh_nodes * num_dofs_per_mesh_node * l_score_pmf[i] )
Z = createSamplingMatrix(input_dict, l_score_pmf, sample_mesh_nodes)

# output sample mesh nodes to ascii file
OutputSampleMeshNodes(sample_mesh_nodes)

# output sampling matrix in sparse format (i,j,Z_ij)
OutputSamplingMatrix( Z )


# write out sample mesh nodes
writeSampleMeshNodesToFile(input_dict, mask_obj)

```

**Comment by pjb236** [comment]
Seems like the main routine we need to implement is something to sample with replacement over a distributed vector of probabilities.

**Comment by fnrizzi** [comment]
@pjb236 
thanks for pushing the branch and the code! 

Here are some comments (please): 
- can you please add a test for leverage scores that uses dofsPerMeshNode > 1

- the current lev score test creates the matrix inside the python test script itself. Can you please add another test where we actually use the driver script to read the matrix from file? 

- can you please add error/exception handling to the IO and levscore code? For example if the resulting lev scores array is empty, what to do then, or checking that the indices selected are positive, etc. 

- can you please remove all the TODOs inside the code and turn them into separate github issues? 
it is hard to keep track of those things buried inside the code. 

- the filename to pass to the yaml file `  residual-basis-root-name: "matrix.bin"`, is it supposed to be a fullpath? 

- the entry `num-mesh-nodes:` is the numnodes for the full mesh? 

- I saw that now the format for data file is `matrix.bin.3.0` where 3 is the number of ranks, right? Can you please remove the 3? It is redundant since we already know the total ranks/files and removing it makes for one less thing to think of. 

- here is what I expect one to do to run the levscore driver:
  ```
  mpirun -np n python3 hypred_levscores.py --input <full-path-to-input-file> 
  ```
  we would need to specify an output directory where to put all the output of the code, e.g. the sample mesh indices file, any log, etc 
 
- i think in the input file we should add an entry for where the basis files are located, something like
```yaml
ResidualBasis: 
  files-dir: <full-path-to-where-files-are>
```

- I think we can simplify a bit the input yaml file since some nodes have redundant names. This is my suggestion: 
```yaml
ResidualBasis: 
  file-root-name: "matrix.bin"
  format: "binary"
  num-columns: 4
  num-mesh-nodes: 15
  dofs-per-mesh-node: 1
SampleMesh: 
  target-num-nodes: 8
  leverage-score-beta: 0.5
  seed-nodes-file: "seed.txt" # Optional 
```

- can you please complete the demo inside `pressio-toold/demos/levscores`? We would need to add file with data to demonstrate how to run the lev scores. See also readme. 

- in the IO test, we have binary files inside committed to the repo. This is not going to work. Can you please remove those? 
To test the binary IO we need to generate the binary data as part of the test, writing to file, and then reading them. We cannot use binary files commited to git. 

Just a detail but when you commit, please use `#issuenumber` in the commit message so that it shows up here and we can link to it directly. Don't mean to be annoying, just to keep track of things :)

**Comment by pjb236** [comment]
@fnrizzi 
To address some of your questions:

> the entry num-mesh-nodes: is the numnodes for the full mesh?

Yes, any ideas on a more informative name?

> we would need to specify an output directory where to put all the output of the code, e.g. the sample mesh indices file, any log, etc

Related to this, do you have a strong preference to run the script from the driver-scripts directory? I set it up so it would be run as follows:

```
mpirun -np n python3 <path-to-driver-scripts>hypred_levscores.py --input <yaml-file-name>
```

I am not married to this, but this choice obviously impacts how we specify an output directory.

**Comment by fnrizzi** [comment]
> > the entry num-mesh-nodes: is the numnodes for the full mesh?
> Yes, any ideas on a more informative name?

What about `global-mesh-size` or `global-num-mesh-nodes`?

> > we would need to specify an output directory where to put all the output of the code, e.g. the sample mesh indices file, any log, etc
> Related to this, do you have a strong preference to run the script from the driver-scripts directory? I set it up so it would be run as follows:
> 
> ```
> mpirun -np n python3 <path-to-driver-scripts>/hypred_levscores.py --input <yaml-file-name>
> ```
> 
> I am not married to this, but this choice obviously impacts how we specify an output directory.

I think this is fine, but why it would impact how we specify the output directory?

**Comment by pjb236** [comment]
Really it just impacts whether or not the output directory can/should have a default value. If I always run the script from the repo, an output directory needs to be required. If it can be run anywhere, then defaulting to the working directory makes sense.

**Comment by fnrizzi** [comment]
@pjb236 
Do you think we should keep a default output directory? If so, leaving the "current directory where the command is issued from" is fine for me.

**Comment by pjb236** [comment]
> @pjb236
> Do you think we should keep a default output directory? If so, leaving the "current directory where the command is issued from" is fine for me.

Yeah, that's what I meant by "default directory", sorry I didn't make that clearer!

**Comment by fnrizzi** [comment]
no no, that is fine! I hope that does not cause troubles with the Python environemt and finding the modules and such
